%This documents the struct containing the settings from the
%egm_Sorted_rasters GUI. This struct is generated by
%getSortedRasterParameters and used by sorted_rasters.
%
%See sorted_rasters_parameters.pptx in this folder to see a labeled diagram
%showing each parameter and the GUI object it corresponds to.
%
%Output (default = 'raster')
%	If 'raster', the function creates a figure containing only the raster
%	and closes the sorted raster GUI when finished. The function returns a
%	handle to the raster figure.
%	If any other string, the function
%
%Default values for the remaining parameters are taken from
%egm_Sorted_rasters
%
%  FileRange
%     List of file numbers to include. FileRange corresponds to the 'File
%     range' button in the top left corner of the GUI.
%  TriggerSource
%      Can be the string 'Sound' or an event number from the dbase. If you
%      are unsure which is the correct event number, use dbaseEventNames()
%      to see the name for each event number. This corresponds to the
%      'Source' popup box in the Trigger panel in the top left corner of
%      the GUI.
%  TriggerType
%  	  TriggerType corresponds to the 'Type' popup menu in the 'Trigger'
%  	  panel on the left side. It must be one of the strings listed in this
%  	  popup box. If TriggerSource is 'Sound', TriggerType can be
%  	  'Syllables', 'Motifs', or 'Bouts'. Otherwise, TriggerType can be
%  	  'Events', 'Bursts', 'Burst events', 'Single events', or 'Pauses'
%  Alignment
%    String controlling alignment of the trigger (t=0 on the raster). Value
%    can be 'onset', 'offset', or 'midpoint'. It corresponds to the
%    'Alignment' popup menu in the 'Trigger' panel on the left side.
%
%The following parameters correspond to the 'Options' button in the
%'Trigger' panel on the left side EventSource. Each of these options is
%specific to a particular TriggerType. 
%
%  TriggerSyllIncluded
%      When the trigger is 'Syllables', this is a string of syllable labels
%      to include in the raster. For example, 'abe' would include only
%      syllables labeled 'a', 'b', and 'e', but not syllables labeled 'c'
%      or 'd'.
%  TriggerSyllExcluded
%      When the trigger is 'Syllables', this is a string of syllable labels
%      to exclude from the raster. For example, 'cd' would make a raster
%      that has syllables with all labels EXCEPT 'c' and 'd'.
%  TriggerMotifSequence
%      When the trigger is 'Motifs', this specifies the syllable sequences
%      that form a motif. It is a cell array of strings where each string
%      is a valid motif sequence. For example, {'xyz', 'yyz'} would find
%      motifs with the sequence 'x' followed by 'y' followed by 'z' as well
%      as 'y' followed by 'y' followed by 'z' (but not xxz). If there is
%      only one sequence, it still needs to be in a cell array.
%  TriggerMotifMaxGap
%      When the trigger is 'Motifs', this specifies the max gap between
%      syllables in the motif, in seconds.
%  TriggerBoutInterval
%      When trigger is 'Bouts', this specifies the maximum gap between
%      syllables in the bout, in seconds.
%  TriggerBoutMinDuration
%      When trigger is 'Bouts', this specifies the minimum duration of a
%      bout, in seconds.
%  TriggerBoutMinSyllCount
%      When trigger is 'Bouts', this specifies the minimum number of
%      syllables in a bout.
%  TriggerBurstMinFreq
%      When trigger is 'Bursts', 'Burst events', or 'Single events', this
%      specifies the minimum frequency of events in a burst, in Hz.
%  TriggerBurstMinCount
%      When trigger is 'Bursts', 'Burst events', or 'Single events', this
%      specifies the minimum number of events in a burst.
%  TriggerPauseMinDuration
%      When trigger is 'Pauses', this specifies the minimun duration of a
%      pause, in seconds.
%
%The following parameters all correspond to the 'Events' panel on the left
%side of the GUI. They are the same as the parameters for the trigger
%described above, but they apply to events instead.
%
%  EventSource
%  EventType
%  EventSyllIncluded
%  EventSyllExcluded
%  EventMotifSequence
%  EventMotifMaxGap
%  EventBoutInterval
%  EventBoutMinDuration
%  EventBoutMinSyllCount
%  EventBurstMinFreq
%  EventBurstMinCount
%  EventPauseMinDuration
%
%The following parameters all correspond to the 'Filtering panel in the
%bottom left corner of the GUI. The values of these parameters is each a
%two-element vector specifying the minimum and maximum value for each
%feature. Trials are omitted from the raster if any feature is not within
%the specified limits. If you want a feature to be ignored, set its
%parameter to [-Inf Inf].
%
%  FilterByTriggerDuration
%  FilterByPrevTriggerOnset
%  FilterByPrevTriggerOffset
%  FilterByNextTriggerOnset
%  FilterByNextTriggerOffset
%  FilterByPrevEventOnset
%  FilterByPrevEventOffset
%  FilterByNextEventOnset
%  FilterByNextEventOffset
%  FilterByFirstEventOnset
%  FilterByFirstEventOffset
%  FilterByLastEventOnset
%  FilterByLastEventOffset
%  FilterByNumberOfEvents
%  FilterByIsInEvent
%
%The following parameters correspond to the controls that are below the
%raster.
%
%  BackgroundColor
%      BackgroundColor corresponds to pushing the 'Colors' button under the
%      axes and choosing 'Background'. It is specified as RGB (3-element
%      vector).
%  Hold
%      Hold corresponds to the 'Hold on to add events' checkbox under the
%      axes. Its value can be 'on' or 'off'. If it is 'on', many controls
%      in the GUI are disabled. It allows you to add another set of events
%      on top of whatever events are already plotted. Both event sets must
%      use the same trigger settings and the same sorting parameters.
%  SkipSorting
%      SkipSorting corresponds to the 'Skip sorting' checkbox under the
%      axes.
%
%The following parameters correspond to the 'Window' panel at the bottom of
%the GUI.
%
%  WindowLimits
%      WindowLimits corresponds to the 'Window limits' button. It is a
%      two-element vector where the first element amount of time before the
%      start reference point included in the window. The second element is
%      the amount of time after the end reference point included in the
%      window. Both elements are positive numbers in seconds. The onset and
%      offset reference points are set with the parameters below.
%  StartReference
%      StartReference corresponds to the 'Start reference' popup menu. It
%      sets the start reference point for the WindowLimits. It can be
%      'Previous onset', 'Previous offset', 'Current onset', 'Current
%      midpoint', 'Current offset', or 'First warp point'.
%  StopReference
%      StopReference corresponds to the 'Stop reference' popup menu. It
%      sets the end reference point for the WindowLimits. It can be
%      'Current onset', 'Current midpoint', 'Current offset', 'Next onset',
%      'Next offset', or 'Last warp point'.
%  LockLimitsToTrigger
%      LockLimitsToTrigger corresponds to the 'Lock limits to trigger'
%      checkbox. If this is true, the onset and offset refrences are both
%      set to 'Current onset'.
%  ExcludePartialWindows
%      ExcludePartialWindows corresponds to the 'Exclude partial windows'
%      checkbox. If the value of this parameter is true, trials are
%      excluded if their windows extend beyond a data file boundary.
%  ExcludePartialEvents
%      ExcludePartialEvents corresponds to the 'Exclude partial events'
%      checkbox. If the value of this parameter is true, any events are
%      excluded if they extend beyond the window boundaries.
%  
%The following parameters correspond to the 'Exporting' panel at the bottom
%of the GUI.
%
%  ExportHeightUnits
%      ExportHeightUnits corresponds to the 'Height units' radio buttons.
%      Its value can be 'Absolute', 'Per trial', or 'Per time'.
%  ExportHeight
%      ExportHeight corresponds to the height set by pushing the
%      'Dimensions' button. The units on this number depend on the setting
%      of ExportHeightUnits. For 'Absolute', ExportHeight is in inches. For
%      'Per trial', ExportHeight is in inches per trial. For 'Per time',
%      ExportHeight is in inches per second.
%  ExportWidthUnits
%      ExportWidthUnits corresponds to the 'Width units' radio buttons. Its
%      value can be 'Absolute' or 'Per time'.
%  ExportWidth
%      ExportWidth corresponds to the width set by pushing the 'Dimensions'
%      button. The units on this number depend on the setting of
%      ExportWidthUnits. For 'Absolute', ExportWidth is in inches. For 'Per
%      time', ExportWidth is in inches per second.
%  ExportPSTHHeight 
%      ExportPSTHHeight corresponds to the height of the peristimulus time
%      histogram set by pushing the 'Dimensions' button. It is always in
%      inches.
%  ExportHistHeight
%      Same as ExportPSTHHeight, but for the vertical histogram.
%  ExportInterval
%      ExportInterval corresponds to the distance between the subplots, in
%      inches. In the GUI, it is set by pushing the 'Dimensions' button.
%  ExportResolution
%      ExportResolution corresponds to the resolution (in dots per inch) of
%      the exported figure. In the GUI, it is set by pushing the
%      'Dimensions' button. 
%  
%The following parameters correspond to the 'Sorting' panel in the top
%right corner of the GUI.
%
%  PrimarySortBy
%      PrimarySortBy corresponds to the 'Primary sort' popup menu. Trials
%      are ordered by this feature.
%  SecondarySortBy
%      SecondarySortBy corresponds to the 'Secondary sort' popup menu.
%      Trials are ordered by this feature if they have the same value for
%      the primary sort feature.
%  PrimarySortDirection
%      PrimarySortDirection corresponds to the 'Descending' checkbox for
%      primary sort. Its value can be 'ascending' or 'descending'.
%  SecondarySortDirection
%      SecondarySortDirection corresponds to the 'Descending' checkbox for
%      secondary sort. Its value can be 'ascending' or 'descending'.
%  PrimarySortGroupLabels
%      PrimarySortGroupLabels corresponds to the 'Group labels' checkbox.
%      Its value can be true or false. I'm not sure what this does.
%
%The following parameters correspond to the 'Raster' panel on the right
%side of the GUI. In this panel, there is a list box with all of the
%elements that can appear in the raster. When selecting each one
%
%  RasterElements
%     RasterElements is a struct array, with each element corresponding
%     with one of the objects that can be displayed. Each element has these
%     properties:
%
%     RasterElements(n).Name 
%         is the name of the n-th element, as it appears in the 'Objects'
%         listbox.
%     RasterElements(n).Include
%         is 1 if the n-th element is included in the plot. This
%         corresponds to the 'Include' checkbox.
%     RasterElements(n).Continuous
%         is 1 if the n-th element should be plotted as a continuous line
%         or 0 if it should be plotted as ticks. It corresponds to the
%         'Continuous' checkbox. This checkbox is disabled for some raster
%         objects. Those objects ignore this parameter.
%     RasterElements(n).Color
%         is the color of the n-th element as an RGB triplet. It
%         corresponds to the 'Color' button in the 'Raster' panel.
%     RasterElements(n).Param
%         is the width or transparency of the n-th element. This
%         corresponds to the 'Width' or 'Transparency' button (to the right
%         of the 'Color' button). Depending on the name of the raster
%         element, this will be interpreted as either width or
%         transparency. To find out which, select the element from the
%         'Objects' list box and look at the name of the button.
%
%  RasterXLim
%      Corresponds to the 'Time limits' button. This is a two-element
%      vector with the min and max time displayed on the x axis, in
%      seconds.
%  RasterXLimAuto
%      Corresponds to the 'Auto limits' check box. If this is 1, RasterXLim
%      is ignored and WindowLimits are used as the x limits.
%  RasterTrialHeightUnits
%      Correspodns to the 'Trial height' radio buttons. Its value can be
%      'Trials', 'Seconds', 'Inches', or 'Percent'.
%  RasterTrialHeight
%      Corresponds to pushing the 'Trial height' button. The units on this
%      number are set by the RasterTrialHeightUnits parameter. 
%  RasterTrialOverlap
%      Overlap in percent. Corresponds to pushing the 'Trial height' button
%      when the RasterTrialHeightUnits are 'Inches'.
%  RasterInchesPerSec
%      When RasterYAxis is 'Time' and RasterTrialHeightUnits is 'Inches',
%      this controls the scale of the axis. Corresponds to pushing the
%      'Trial height' button.
%  RasterYAxis
%      Units on the y axis. Corresponds to the 'Y axis' radio buttons.
%      Valid options are 'Trial #' and 'Time'.
%
%The following parameters correspond to the 'Histograms' panel in the
%bottom right corner of the GUI. In this panel, most of the controls can
%affect either the PSTH or the vertical histogram, depending on which
%button is set. In this function, there are separate parameters for the
%PSTH and vertical histogram settings, which are listed together below.
%
%  PsthShow / VerticalHistogramShow
%      Corresponds to the 'Show' checkbox. If set to 1, the histogram is
%      shown.
%  PsthBinSize / VerticalHistogramBinSize
%      Size of histogram bins, in seconds. Corresponds to pushing the
%      'Options' button
%  PsthYLim / VerticalHistogramYLim
%      Y limits for histograms. The units on this number depend on
%      Corresponds to pushing the 'Options' button. This parameter is only
%      used if the parameter HistogramYLimMode is 'Manual'.
%  PsthSmoothing / VerticalHistogramSmoothing
%      Number of bins in the smoothing window. Set to 1 for no smoothing.
%      This corresponds to pushing the 'Options' button.
%  PsthYUnits / VerticalHistogramYUnits
%      Units for the Y axis of the histogram. This corresponds to the
%      'Axis' popup menu. Value can be 'Rate (Hz)', 'Count per trial', or
%      'Total count'. For VerticalHistogramYUnits, it can also be 'Fraction
%      of time', 'Time per trial', or 'Total time'.
%  PsthCount / VerticalHistogramCount
%      This parameter controls what is counted in the histograms. It
%      corresponds to the 'Count' popup menu. Its value can be 'Onsets',
%      'Offsets', or 'Full duration'.
%  VerticalHistogramROI
%      Sets the time window for a region of interest, in seconds. The
%      vertical histogram will only include data from inside the ROI. This
%      is a two-element vector containing the start and stop times of the
%      ROI. It corresponds to pressing the 'Options' button.
%  HistogramYLimMode
%      Corresponds to the 'Axis limits' radio buttons. If it is set to
%      'Manual', the y limits for the histograms are determined by the
%      parameters PsthYLim and VerticalHistogramYLim. If set to 'Auto', the
%      y limits are determined automatically to fit the data.
%  
%See also: SORTED_RASTERS, GETSORTEDRASTERPARAMETERS